### ISSUE TITLE
Crash in arm64-v8a devices

### ISSUE THREAD

**Issue by nmilcoff** [strazzere/anti-emulator#14]
As the title says, the app crashes immediately in [this line](https://github.com/strazzere/anti-emulator/blob/master/AntiEmulator/src/diff/strazzere/anti/MainActivity.java#L45) (I think).

Perhaps it is related to #12? Any ideas? :) 

Reproduction steps are simple: Just try to run the app in any arm64-v8a powered device.

```java
E/ion: ioctl c0044901 failed with code -1: Invalid argument
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: diff.strazzere.anti, PID: 29146
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/diff.strazzere.anti-73jbD1oseRECGqZbKcNMfg==/base.apk"],nativeLibraryDirectories=[/data/app/diff.strazzere.anti-73jbD1oseRECGqZbKcNMfg==/lib/arm64, /system/lib64]]] couldn't find "libanti.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at diff.strazzere.anti.emulator.FindEmulator.<clinit>(FindEmulator.java:67)
        at diff.strazzere.anti.emulator.FindEmulator.hasKnownDeviceId(FindEmulator.java:170)
        at diff.strazzere.anti.MainActivity.isQEmuEnvDetected(MainActivity.java:45)
        at diff.strazzere.anti.MainActivity$1.run(MainActivity.java:30)
```

**Comment by strazzere** [comment]
It's actually crashing on this line https://github.com/strazzere/anti-emulator/blob/master/AntiEmulator/src/diff/strazzere/anti/emulator/FindEmulator.java#L67

This is because it isn't compiling any 64bit binaries so your system will obviously not find them.

You need to modify this to compile such a binary, and also exclude the arm calls that are going / or update them to arm64.

**Comment by strazzere** [comment]
Much appreciated for reporting and getting a fix out.
