### ISSUE TITLE
why using "==" to compare String in class /FindEmulator.java?

### ISSUE THREAD

**Issue by orangetangerine** [strazzere/anti-emulator#3]
public static boolean hasEmulatorBuild(Context context) {
       //...
        if ((BOARD == "unknown") || (BOOTLOADER == "unknown") || (BRAND == "generic") || (DEVICE == "generic")
                        || (MODEL == "sdk") || (PRODUCT == "sdk") || (HARDWARE == "goldfish")) 
      /...
    }

why using "==" here? Looks like it will always return false...
And I found BOOTLOADER is 'unknown' in some deivces with "other" ROM...

**Comment by strazzere** [comment]
Good catch - it's actually bad practice to be using "==" though in this case it does work (it compares them as literals, not attempting to equate  the objects directly). I'll change this coming up to a better method.

As for the "unknown" being used on different ROMs - I consider those edge cases. The main reasoning behind this project is to detect emulators vs normal devices, I'd consider improperly setup ROMs != normal devices.

Also, I'd hope if people are deploying this into the wild for detection, they potentially use these as part of a risk score; rather than a boolean style usage.
